// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6GXcx0-m43TSUSamP3-GaDOA1JZnLOC4',
    appId: '1:438977939521:web:11ec99d5dab951edfbdec0',
    messagingSenderId: '438977939521',
    projectId: 'hoty-65cd7',
    authDomain: 'hoty-65cd7.firebaseapp.com',
    storageBucket: 'hoty-65cd7.appspot.com',
    measurementId: 'G-RNC6JTJCH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3VzBHgBKl1a4Cs2Xh-Cn1wcy1jKJtwg',
    appId: '1:438977939521:android:537f1b10e3ef73f1fbdec0',
    messagingSenderId: '438977939521',
    projectId: 'hoty-65cd7',
    storageBucket: 'hoty-65cd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgALF9LaPIUHes8ws3ADx17FQHRTjjG2o',
    appId: '1:438977939521:ios:1f01fd4bfbfd78a2fbdec0',
    messagingSenderId: '438977939521',
    projectId: 'hoty-65cd7',
    storageBucket: 'hoty-65cd7.appspot.com',
    androidClientId: '438977939521-2t1f1m3aei412ehno6gi087l2bm5d3gs.apps.googleusercontent.com',
    iosClientId: '438977939521-bkgnu9t70li81a1qt0te41i9barfiubb.apps.googleusercontent.com',
    iosBundleId: 'com.hotyvn.hoty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgALF9LaPIUHes8ws3ADx17FQHRTjjG2o',
    appId: '1:438977939521:ios:1f01fd4bfbfd78a2fbdec0',
    messagingSenderId: '438977939521',
    projectId: 'hoty-65cd7',
    storageBucket: 'hoty-65cd7.appspot.com',
    androidClientId: '438977939521-2t1f1m3aei412ehno6gi087l2bm5d3gs.apps.googleusercontent.com',
    iosClientId: '438977939521-mdjqf9mca3fgvbc31svd6k8k25j2ng8e.apps.googleusercontent.com',
    iosBundleId: 'com.hotyvn.hoty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6GXcx0-m43TSUSamP3-GaDOA1JZnLOC4',
    appId: '1:438977939521:web:9a0228a28b6d0121fbdec0',
    messagingSenderId: '438977939521',
    projectId: 'hoty-65cd7',
    authDomain: 'hoty-65cd7.firebaseapp.com',
    storageBucket: 'hoty-65cd7.appspot.com',
    measurementId: 'G-VYS4ZT8K6G',
  );
}