include: package:lints/recommended.yaml

analyzer:
  exclude: [example/explorer/**]
  language: 
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors: 
    todo: ignore
      
linter:
  rules:
    # Some additional lints we want to enforce
    always_declare_return_types: true
    avoid_type_to_string: true
    cascade_invocations: true
    discarded_futures: true
    directives_ordering: true
    invalid_case_patterns: true
    leading_newlines_in_multiline_strings: true
    literal_only_boolean_expressions: true
    no_default_cases: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    type_literal_in_constant_pattern: true
    unawaited_futures: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_super_parameters: true

    # This is a good lint, but
    # https://github.com/microsoft/win32metadata/issues/99 makes it impossible
    # to resolve today.
    library_private_types_in_public_api: false

    # Unnecessary in most cases, but avoids accidental name clashes.
    unnecessary_this: false